# -*- coding: utf-8 -*-
"""Proyecto1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-QRRGkpFXDWKu7fiCMTt6OChF_mc2yKh
"""

# -----------  Menu  -------------
def Menu():
    # -- Mostrar el menú de opciones
    print()
    print('*****   SECUENCIAS   *****')
    print('1 Agregar')
    print('2 Listar')
    print('3 Bacteria Infecciosa')
    print('4 FIN')

# -----------  Módulo Agregar  -------------
def Agregar(Lista):    
    # -- Leer el nombre de la bacteria
    NombreBacteria = input('Ingrese el nombre de la bacteria : ')
    if Posicion(NombreBacteria,Lista) >= 0:
        print('La bacteria ya esta registrada')
    else:
        # Ingresar la secuenciamiento genetico
        secuencia = input('Ingrese la secuencia : ')
        # Agregar a la lista
        Lista.append([NombreBacteria, secuencia])

# -----------  Módulo Posicion  -------------
def Posicion(secuencia, Lista):
    # -- Inicializar contadores
    P = -1
    I = 0
    # -- Buscar mientras no se haya encontrado el elemento y aún existan elementos por comparar
    while (P == -1) and (I < len(Lista)):
        if (Lista[I][0] == secuencia):
            # -- Si se encontró el elemnto, el índice es la posición del elemento en la lista
            P = I
        else:
            # -- Si no se encontró el elemento, incrementar el índice
            I += 1
    # Retornar posición
    return P
# -----------  Listar  -------------
def Listar(Lista):
    # -- Listar las secuencias
    print()
    print("LISTADO DE SECUENCIAS")
    print("=====================")
    print('Bacteria\tSecuencias')
    print('--------\t--------')
    for A in Lista:
        Posicion = A[1]
        print(A[0],'\t', Posicion)

# ---------Comparar Secuencia-------
def Secuencias(SecuenciaInfecciosa,Lista):
  for i in Lista:
    cont=0
    menor=10
    for j in range(len(i[1])):
      if i[1][j]!=SecuenciaInfecciosa[j]:
        cont+=1
        proxima=i[0]
        print(cont,"---",proxima)

# ---------PROGRAMA PRINCIPAL----------
# Secuencia a ser identificada 
SecuenciaInfecciosa='ACATT'
# -- Declarar la lista
Lista = []
# -- Mostrar y procesar Menu
Opcion = 0
while Opcion != 4:
    # -- Mostrar menu
    Menu()
    # -- Leer opción
    Opcion = int(input('Ingrese opción --> '))
    # -- Procesar de acuerdo a opción
    if Opcion == 1:
        Agregar(Lista)
    elif Opcion == 2:
        Listar(Lista)
    elif Opcion == 3 :
      Secuencias(SecuenciaInfecciosa,Lista)