# Eso es una plantilla de solicitud de características que se puede utilizar para sugerir una idea o mejora para un proyecto. La plantilla incluye una serie de secciones que proporcionan información detallada sobre la idea o mejora y cómo podría implementarse.
# 
# La sección "Is your feature request related to a problem?" proporciona una descripción clara y concisa del problema o frustración que se está experimentando. La sección "Describe the solution you'd like" proporciona una descripción clara y concisa de lo que se quiere que suceda. La sección "Describe alternatives you've considered" proporciona una descripción clara y concisa de las soluciones o características alternativas que se han considerado.
# 
# La sección "Additional context" proporciona cualquier otro contexto o capturas de pantalla relevantes sobre la solicitud de características.
# 
# Esta plantilla se puede utiliz

name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint revChatGPT
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
