# Este código es una lista de repositorios y ganchos de pre-commit. Pre-commit es una herramienta que se ejecuta automáticamente antes de hacer un commit en Git. Estos ganchos pueden ser utilizados para realizar diversas tareas de revisión de código, tales como detectar errores de sintaxis o buscar código poco legible.
# 
# Cada repositorio en la lista se refiere a un conjunto de ganchos que pueden ser utilizados para realizar tareas de revisión de código. Por ejemplo, el repositorio "pre-commit/pre-commit-hooks" incluye ganchos para detectar espacios en blanco al final de las líneas, corregir problemas de formato de archivos y buscar declaraciones de depuración en el código.
# 
# Los ganchos de cada repositorio tienen una ID única y, en algunos casos, pueden tener argumentos adicionales para controlar su comportamiento. Por ejemplo, el gancho "autopep8" del repositorio "pre-commit/mirrors-autopep8" tiene argumentos para habilitar la eliminación agresiva de espacios en blanco y mostrar mensajes de depuración durante su ejecución.
# 
# Esta lista de repositorios y ganchos de pre-commit se utiliza para configurar Pre-commit para realizar diversas tareas de revisión de código en un proyecto de software.


repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
        args: [--py37-plus]
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.3.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.0
    hooks:
    -   id: autopep8
        args:
        - --aggressive
        - --verbose
        - -d
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]
-   repo: https://github.com/pycqa/pylint
    rev: v2.15.8
    hooks:
    -   id: pylint
        args:
        - --max-line-length=80
        - --ignore-imports=yes
        - -d duplicate-code
