name: Python package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Packing
      run: |
        pyinstaller -i ./img/calendar.ico -n NUAA_iCal_${{ matrix.os }} -F main.py
              
    - name: Upload to artifact
      uses: actions/upload-artifact@v2
      with:
        name: NUAA_iCal_${{ matrix.os }}
        path: ./dist/
